name: QA - Run Maven Tests
on:
  workflow_dispatch:
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test verify
    - name: Copy Test Results
      if: always()
      run: |
          mkdir -p resultsFolder
          pwd
          ls
          mv /home/runner/work/restApiFrm_sample/restApiFrm_sample/target/surefire-reports* resultsFolder  
    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: RunReports
        path: resultsFolder
        
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: TestNG Report
        path:  resultsFolder/surefire-reports/TEST-TestSuite.xml                            
        reporter: java-junit
